---
- name: install initial packages on all boxes
  hosts: ntpservers
  remote_user: ansible
  become: yes
  
  tasks:
  - name: configure chrony
    template:
      src: /ansible/templates/chrony.conf.j2
      dest: /etc/chrony.conf
    notify: 
      - restart chronyd

  - name: start chronyd
    service: 
      name: chronyd 
      state: started 
  - name: restart service
    service:
      name: chronyd
      state: restarted
