---

- name: Configuring ldap server
  hosts: ldapserver
  remote_user: ansible
  become: true

  tasks:
    - name: Update packages
      yum:
        name: '*'
        state: latest
  roles:
    - ldap
