---
# tasks file for repo

- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: "*"
    state: absent
  notify: yum-clean-metadata

- name: yum-clean-metadata
  command: yum clean all
  args:
    warn: no

- name: Add multiple repositories into the same file (1/5)
  yum_repository:
    name: base
    description: CentOS-$releasever - Base
    file: centoslocal.repo
    baseurl: http://192.168.32.17/$releasever/os/$basearch/
    gpgcheck: yes
    enabled: yes

- name: Add multiple repositories into the same file (2/5)
  yum_repository:
    name: updates
    description: CentOS-$releasever - Updates
    file: centoslocal.repo
    baseurl: http://192.168.32.17/$releasever/updates/$basearch/
    gpgcheck: yes
    enabled: yes

- name: Add multiple repositories into the same file (3/5)
  yum_repository:
    name: extras
    description: CentOS-$releasever - Extras
    file: centoslocal.repo
    baseurl: http://192.168.32.17/$releasever/extras/$basearch/ 
    gpgcheck: yes
    enabled: yes

- name: Add multiple repositories into the same file (4/5)
  yum_repository:
    name: centosplus
    description: CentOS-$releasever - Plus
    file: centoslocal.repo
    baseurl: http://192.168.32.17/$releasever/centosplus/$basearch/
    gpgcheck: yes
    enabled: yes

- name: Add multiple repositories into the same file (5/5)
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    file: centoslocal.repo
    baseurl: http://192.168.32.17/epel/$releasever/$basearch/
    gpgcheck: yes
    enabled: yes


